# Generated by Django 3.0.8 on 2020-07-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_games'),
    ]

    operations = [
    ]
