# Generated by Django 3.0.8 on 2020-07-20 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('release_year', models.IntegerField()),
                ('time_to_complete', models.IntegerField(null=True)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(max_length=150)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.User')),
            ],
            options={
                'unique_together': {('username', 'preference')},
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('single_player', models.BooleanField()),
                ('multiplayer', models.BooleanField()),
                ('cooperative', models.BooleanField()),
                ('mods', models.BooleanField()),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
            options={
                'unique_together': {('game_name', 'platform_name')},
            },
        ),
    ]
