# Generated by Django 3.0.8 on 2020-08-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pwd',
            new_name='password',
        ),
    ]
